### ISSUE TITLE
Problem with plugin iv RC 1.3.3

### ISSUE THREAD

**Issue by bilbolodz** [arodier/Roundcube-Plugins#30]
I'm trying update my RC from 1.2.X to 1.3.X and got an error with vacation_sieve plugin.

`[14-Nov-2017 13:45:22 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function Q() in /var/www/roundcubemail-1.3.3/plugins/vacation_sieve/vacation_sieve.php:293
Stack trace:
#0 /var/www/roundcubemail-1.3.3/program/include/rcmail_output_html.php(1146): vacation_sieve->vacation_sieve_form(Array)
#1 [internal function]: rcmail_output_html->xml_command(Array)
#2 /var/www/roundcubemail-1.3.3/program/include/rcmail_output_html.php(1014): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')
#3 /var/www/roundcubemail-1.3.3/program/include/rcmail_output_html.php(635): rcmail_output_html->parse_xml('<roundcube:obje...')
#4 /var/www/roundcubemail-1.3.3/program/include/rcmail_output_html.php(489): rcmail_output_html->parse('plugin', false)
#5 /var/www/roundcubemail-1.3.3/plugins/vacation_sieve/vacation_sieve.php(95): rcmail_output_html->send('plugin')
#6 /var/www/roundcubemail-1.3.3/program/lib/Roundcube/rcube_plugin_api.php(493): vacation_sieve->vacation_sieve_init()
#7 /var/www/roundcubemail-1.3.3/index.php(289): rcube_plugin_api->exe in /var/www/roundcubemail-1.3.3/plugins/vacation_sieve/vacation_sieve.php on line 293`

**Comment by bilbolodz** [comment]
To get these working you have to replace all `Q(` calls with: `rcube::Q(`

**Comment by bilbolodz** [comment]
Generally there are a lot more problems with these plugin in RC 1.3: many function which in 1.2 has been marked as deprecated in 1.3 are removed.

**Comment by nicorac** [comment]
I'm actually using vacation_sieve, so I've fixed it to make it run with RoundCube 1.3.

Here's the repository:
https://github.com/nicorac/vacation_sieve

Hope it helps...
